site_name: CHAOAJ - Alvin Chao
site_url: https://chaoaj.github.io

theme: pulse


nav:
    - Home: index.md
    - About: about.md
    - Canvas: https://canvas.jmu.edu/
    - Gradescope: https://www.gradescope.com/
    - Resources: resources.md
